[changelog]
header = "# Changelog\n\n"
body = """
{% if version %}\
## {{ version }} ({{ timestamp | date(format="%Y-%m-%d") }})
{% else %}\
## Unreleased
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | upper_first | trim }}\
{% endfor %}
{% endfor %}

"""
footer = ""
trim = true

[git]
conventional_commits = true
filter_unconventional = true  # silently drop chore/refactor/docs/test
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^feat!", group = "Breaking Changes" },
]
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
sort_commits = "oldest"
